@extends('layout.layout')
@section('container')
<!--banner starts-->
<div class="banner-area pt-60 pt-sm-55 pb-100 pb-sm-80">
  <div class="container">
    <div class="row banner-caption align-items-center">
      <div class="col-lg-7 col-md-6">
        <div class="wow fadeInUp">
          <h5>Digital Business</h5>
        </div>
        <div class="wow fadeInUp" data-wow-delay=".3s">
          <h1><span>Buy App Reviews</span></h1>
        </div>
        <div class="wow fadeInUp" data-wow-delay=".4s">
          <h1 class="mb-20"><span>From Real Users</span></h1>
        </div>
        <div class="wow fadeInUp" data-wow-delay=".5s">
          <p>Our iOS, Android, and macOS high professional reviewers will install, rate, and review your app only in a positive manner. Just make your order and see the fantastic results.</p>
        </div>
      </div>
      <div class="col-lg-5 col-md-6">
        <div class="banner-image wow fadeIn" data-wow-delay=".6s">
          <img src="{{ asset('front_assets/images/banner/rating.png')}}" alt="" />
        </div>
      </div>
    </div>
  </div>
</div>
<!--banner ends-->

<!--about starts-->
<div class="about-area pt-97 pt-sm-77 br-top-ebebeb">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-title text-center mb-45 wow fadeInUp" data-wow-delay=".3s">
          <h2><span>How Do We Function?</span></h2>
          <p class="mt-15">The reviews generated by us are flexible, reliable and even scalable. With US, you can improve your
            <br /> organic search engine ranking of your Android/iOS app on Google Play Store in just three steps:</p>
        </div>
      </div>
      <div class="col-lg-5 offset-lg-1">
        <ul class="list-none list-sign wow fadeInUp" data-wow-delay=".4s">
          <li>Choose from our various packages as per your requirement and budget</li>
          <li>You can find your reviews and ratings increase every day.</li>
          <li>Get the results</li>
        </ul>
      </div>
      <div class="col-lg-6">
        <ul class="list-none list-sign wow fadeInUp" data-wow-delay=".5s">
          <li>Our Reviewers’ Team installs your app and uses it. After that, they rate it and review it.</li>
          <li>Select the service package that you need</li>
          <li>Reviews and ranking</li>
        </ul>
      </div>
    </div>
    <div class="row mt-90 mt-sm-70 align-items-center">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="counter-single">
          <i class="ti-heart-broken"></i>
          <span class="count1">920</span>
          <h4>Customers</h4>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="counter-single">
          <i class="ti-bar-chart"></i>
          <span class="count2">8630</span>
          <h4>Keywords Rank</h4>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="counter-single">
          <i class="ti-check-box"></i>
          <span class="count3">570</span>
          <h4>Projects Completed </h4>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="counter-single">
          <i class="ti-crown"></i>
          <span class="count4">40</span>
          <span>+</span>
          <h4>Awards Win</h4>
        </div>
      </div>
    </div>
  </div>
</div>
<!--about ends-->

<!--services starts-->
<div class="services-area pt-95 pt-sm-75 pb-45 pb-sm-30">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="section-title mb-40">
          <h2><span>Our Services</span></h2>
          <p>Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est
            laborum. </p>
        </div>
        <div class="ds-sm-none">
          <div class="wow fadeIn">
            <img src="{{ asset('front_assets/images/services/people-holding-gold-stars.png')}}" alt="" />
          </div>
        </div>
      </div>
      <div class="col-lg-5 offset-lg-1">
        <div class="service-single wow fadeInUp mt-05" data-wow-delay=".3s">
          <i class="ti-mobile"></i>
          <div class="service-single-brief">
            <h4><span>Digital Marketing</span></h4>
            <p>Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est
              laborum. </p>
          </div>
        </div>
        <div class="service-single wow fadeInUp" data-wow-delay=".4s">
          <i class="ti-twitter"></i>
          <div class="service-single-brief">
            <h4><span>Social Media</span></h4>
            <p>Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est
              laborum. </p>
          </div>
        </div>
        <div class="service-single wow fadeInUp" data-wow-delay=".5s">
          <i class="ti-announcement"></i>
          <div class="service-single-brief">
            <h4><span>SEO Services</span></h4>
            <p>Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est
              laborum. </p>
          </div>
        </div>
        <div class="service-single wow fadeInUp" data-wow-delay=".6s">
          <i class="ti-desktop"></i>
          <div class="service-single-brief">
            <h4><span>Web Development</span></h4>
            <p>Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est
              laborum. </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--services ends-->

<!--benefits and call back starts-->
<div class="benefit-callback bg-f3f8f8 pt-100 pt-sm-80 pb-62 pb-sm-80">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="section-title mb-40">
          <h2><span>Top 4 Benefits Of SEO</span></h2>
          <p>We work with you to transform your organization, driving bold ideas and pragmatic solutions.</p>
        </div>
        <div class="service-single style-2 wow fadeInUp" data-wow-delay=".3s">
          <i class="ti-stats-up"></i>
          <div class="service-single-brief">
            <h4><span>Increased Traffic</span></h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt utsa.</p>
          </div>
        </div>
        <div class="service-single style-2 wow fadeInUp" data-wow-delay=".4s">
          <i class="ti-twitter"></i>
          <div class="service-single-brief">
            <h4><span>Cost-effectiveness</span></h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt utsa.</p>
          </div>
        </div>
        <div class="service-single style-2 wow fadeInUp" data-wow-delay=".5s">
          <i class="ti-desktop"></i>
          <div class="service-single-brief">
            <h4><span>Increased site usability</span></h4>
            <p>Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est
              laborum.</p>
          </div>
        </div>
        <div class="service-single style-2 wow fadeInUp" data-wow-delay=".5s">
          <i class="ti-apple"></i>
          <div class="service-single-brief">
            <h4><span>Brand Awareness</span></h4>
            <p>Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est
              laborum.</p>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="contact-form style-1 wow fadeIn ml-80 mt-sm-15" data-wow-delay=".6s">
          <div class="section-title mb-40">
            <h3><span>Request A Call Back</span></h3>
          </div>
          <form>
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Your Website:* ">
            </div>
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Name:* ">
            </div>
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Email:* ">
            </div>
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Phone:* ">
            </div>
            <div class="form-group">
              <select class="form-control" id="exampleFormControlSelect1">
                <option>What kind of service do you want?</option>
                <option>Social Media Marketing</option>
                <option>Search Engine Optimization</option>
                <option>Email Marketing</option>
                <option>Product Review</option>
              </select>
            </div>
            <button class="btn-common mt-25">Submit Now</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!--benefits and call back ends-->

<!--work process starts-->
<div class="work-process-area bg-1 pt-95 pt-sm-75 pb-100 pb-sm-80">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-title text-center">
          <h2><span>Our Work Process</span></h2>
        </div>
      </div>
    </div>
    <div class="row work-process-inner mt-45">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="process-single wow zoomIn" data-wow-delay=".3s">
          <i class="ti-zoom-in"></i>
          <h4>Research</h4>
          <span>01</span>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="process-single wow zoomIn" data-wow-delay=".4s">
          <i class="ti-pencil-alt"></i>
          <h4>Concept</h4>
          <span>02</span>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="process-single wow zoomIn" data-wow-delay=".5s">
          <i class="ti-announcement"></i>
          <h4>Develop</h4>
          <span>03</span>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="process-single wow zoomIn" data-wow-delay=".6s">
          <i class="ti-bar-chart"></i>
          <h4>Test</h4>
          <span>04</span>
        </div>
      </div>
    </div>
  </div>
</div>
<!--work process ends-->

<!--pricing-area starts-->
<div class="pricing-area bg-1 pt-95 pt-sm-75">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-title text-center">
          <h2><span>Pricing Plan</span></h2>
        </div>
      </div>
    </div>
    <div class="tab-content mt-25">
      <div id="monthly" class="tab-pane fade in show active">
        <div class="row pricing-carousel">
          <div class="col-lg-4">
            <div class="pricing-table-single wow fadeInUp" data-wow-delay=".3s">
              <div class="pricing-table-head">
                <h3>Started</h3>
                <p>$250 with 20% Special Discount</p>
                <h4><sup>$</sup>199<span>/per month</span></h4>
              </div>
              <div class="pricing-table-body">
                <ul class="list-sign">
                  <li>Up to 30 Keywords</li>
                  <li>Up to 10 Web Pages</li>
                  <li>Quarterly Ranking Report</li>
                  <li>Bi-Yearly Link Outreach Campaign</li>
                  <li>24/7 Support</li>
                </ul>
                <a href="#" class="btn-common">Get Started</a>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="pricing-table-single highlight wow fadeInDown" data-wow-delay=".4s">
              <div class="pricing-table-head">
                <h3>Professional</h3>
                <p>$250 with 20% Special Discount</p>
                <h4><sup>$</sup>259<span>/per month</span></h4>
              </div>
              <div class="pricing-table-body">
                <ul class="list-sign">
                  <li>Up to 30 Keywords</li>
                  <li>Up to 10 Web Pages</li>
                  <li>Quarterly Ranking Report</li>
                  <li>Bi-Yearly Link Outreach Campaign</li>
                  <li>24/7 Support</li>
                </ul>
                <a href="#" class="btn-common">Get Started</a>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="pricing-table-single wow fadeInUp" data-wow-delay=".5s">
              <div class="pricing-table-head">
                <h3>Enterprise</h3>
                <p>$250 with 20% Special Discount</p>
                <h4><sup>$</sup>399<span>/per month</span></h4>
              </div>
              <div class="pricing-table-body">
                <ul class="list-sign">
                  <li>Up to 30 Keywords</li>
                  <li>Up to 10 Web Pages</li>
                  <li>Quarterly Ranking Report</li>
                  <li>Bi-Yearly Link Outreach Campaign</li>
                  <li>24/7 Support</li>
                </ul>
                <a href="#" class="btn-common">Get Started</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--pricing-area ends-->

<!--testimonial starta-->
<div class="testimonial-area bg-f3f8f8 pt-95 pt-sm-75 pb-117 pb-sm-105">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-title text-center">
          <h2><span>What Clients Say?</span></h2>
        </div>
      </div>
    </div>
    <div class="row mt-50">
      <div class="col-xl-5">
        <div class="ds-sm-none wow fadeIn">
          <img src="{{ asset('front_assets/images/testimonials/review.png')}}" alt="" />
        </div>
      </div>
      <div class="col-xl-7">
        <div class="row testimonial-carousel">
          <div class="col-lg-6">
            <div class="testimonial-single">
              <div class="testimonial-info">
                <div class="testimonial-thumb">
                  <img src="{{ asset('front_assets/images/testimonials/thumb-1.png')}}" alt="" />
                </div>
                <div class="testimonial-name">
                  <h5>Essie Rice</h5>
                  <span>CEO deercreative</span>
                </div>
              </div>
              <div class="testimonial-desc">
                <p>"Your continued support and aggressive technology have convinced me that signing another optimization
                  contract with {{ env('APP_NAME', 'ADMK') }}, Inc. is the best approach in maintaining our edge over the competition”</p>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="testimonial-single">
              <div class="testimonial-info">
                <div class="testimonial-thumb">
                  <img src="{{ asset('front_assets/images/testimonials/thumb-2.png')}}" alt="" />
                </div>
                <div class="testimonial-name">
                  <h5>Flora Cummings</h5>
                  <span>CEO LionsBite</span>
                </div>
              </div>
              <div class="testimonial-desc">
                <p>"Your continued support and aggressive technology have convinced me that signing another optimization
                  contract with {{ env('APP_NAME', 'ADMK') }}, Inc. is the best approach in maintaining our edge over the competition”</p>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="testimonial-single">
              <div class="testimonial-info">
                <div class="testimonial-thumb">
                  <img src="{{ asset('front_assets/images/testimonials/thumb-1.png')}}" alt="" />
                </div>
                <div class="testimonial-name">
                  <h5>Essie Rice</h5>
                  <span>Larry Page</span>
                </div>
              </div>
              <div class="testimonial-desc">
                <p>"Your continued support and aggressive technology have convinced me that signing another optimization
                  contract with {{ env('APP_NAME', 'ADMK') }}, Inc. is the best approach in maintaining our edge over the competition”</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--testimonial ends-->

<!--blog starts-->
<div class="blog-area pt-95 pt-sm-77 pb-90 pb-sm-70">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-title text-center">
          <h2><span>Latest Blogs</span></h2>
        </div>
      </div>
    </div>
    <div class="row blog-carousel mt-45">
      @foreach ($blogs as $blog)
        <div class="col-lg-4">
          <div class="blog-single wow fadeIn" data-wow-delay=".3s">
            <div class="blog-thumb" style="width: 360px;height: 243px;">
              <a href="{{ route('blog-detail',$blog->id) }}"><img class="h-100" src="{{ asset('/assets/admin/img/post/'.$blog->img)}}" alt="" /></a>
            </div>
            <div class="blog-desc mt-30">
              <ul class="blog-category">
                <li><a href="{{ route('blog-detail',$blog->id) }}">{{ Str::substr($blog->title, 0, 17) }}...</a></li>
              </ul>
              <h3><a href="{{ route('blog-detail',$blog->id) }}">{{ Str::substr($blog->description, 0, 54) }}...</a></h3>
              
            </div>
          </div>
        </div>
      @endforeach
    </div>
  </div>
</div>
<!--blog ends-->
@endsection